name: dev-build

on:
  push:
    paths:
      - "llvm.Dockerfile"

jobs:
  build-dev:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: scrin/manylinux2014-llvm
      DOCKER_FILE_PATH: llvm.Dockerfile
      LLVM_VERSION: "11.0.0"

    # TODO: create a action to reuse code. the problem is how to reuse docker-login.
    steps:
      - uses: actions/checkout@master
      - name: Build Docker
        run: |
          docker build . --file ${{env.DOCKER_FILE_PATH}} --tag ${{env.DOCKER_IMAGE_NAME}}:latest
          docker tag ${{env.DOCKER_IMAGE_NAME}}:latest ${{env.DOCKER_IMAGE_NAME}}:LLVM_VERSION

      - name: Login to Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        run: |
          docker push ${{env.DOCKER_IMAGE_NAME}}:latest
          docker push ${{env.DOCKER_IMAGE_NAME}}:LLVM_VERSION
